apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    region: india 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: custom-port
      protocol: TCP
      port: 1234
      targetPort: 1234
  type: NodePort

