apiVersion: v1
kind: ConfigMap
metadata:
  name: mycm2
  namespace: dev
data:
  wasik.conf: |
    Listen 1234

    <VirtualHost *:1234>
        DocumentRoot "/var/www/html"
        <Directory "/var/www/html">
            AllowOverride All
            Require all granted
        </Directory>
        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined
    </VirtualHost>
