apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc1
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-mypvc1
  storageClassName: ""
