# apps-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-apps
  namespace: dev
spec:
  storageClassName: nfs-apps
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
